apiVersion: v1
kind: Service
metadata:
  name: rollouts-active
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo

---

apiVersion: v1
kind: Service
metadata:
  name: rollouts-preview
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec:
#  ingressClassName: nginx
  rules: 
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service: 
            name: rollouts-active
            port:
              number: 80